### ISSUE TITLE
inspiration for ok?

### ISSUE THREAD

**Issue by maelle** [ropensci/crul#138]
I'm using a Python URL checking library via a GitHub Action and noticed two things that might be useful for ok()

* The random user agent setting https://github.com/urlstechie/urlchecker-python/blob/7fd08866c1550bd9746062c00c1c55fcb44b4e92/urlchecker/core/urlproc.py#L182

* There's a retry argument.

**Comment by maelle** [comment]
List of user agents https://github.com/urlstechie/urlchecker-python/blob/7fd08866c1550bd9746062c00c1c55fcb44b4e92/urlchecker/core/urlproc.py#L53

**Comment by sckott** [comment]
thanks @maelle good ideas there. 

we do have `UserAgentProvider` provider in `charlatan`, but I don't want to bring that in as a dependency, better to just use a short list of them as they have

**Comment by maelle** [comment]
And you can mention charlatan's function in the docs :-)

**Comment by sckott** [comment]
yes, good idea

**Comment by maelle** [comment]
Interesting: https://en.m.wikipedia.org/wiki/User_agent#User_agent_spoofing

**Comment by maelle** [comment]
Also, the very end of https://www.scrapehero.com/how-to-fake-and-rotate-user-agents-using-python-3/ but ok() is not for scraping. 

I've read UA spoofing can be viewed a bit as bad practice since it gives some fake traffic but from my perspective checking and fixing the links once in a while ensures traffic to the websites. Just interesting to keep in mind that it might be debated.

**Comment by sckott** [comment]
yeah, that's interesting stuff on UA spoofing. 

good to know on the 2nd link.  Well, we're not rvest, but in a way an http request is scraping in that you are requesting a response from a server of a given url. here we're just trying to see if the server is "up" rather than fetching the content. with a head request there should be no response body, so that's very different from what a scraper would want, but if the user does a get request  with `ok` then that's no different from scraping (we're not scraping, but that doesn't mean the server won't think we are scraping)

**Comment by sckott** [comment]
- added random user agent support
- for retry, opening new issue for that, https://github.com/ropensci/crul/issues/142 more complicated
