### ISSUE TITLE
funky times headers should warn instead of error

### ISSUE THREAD

**Issue by sckott** [ropensci/crul#150]
httr warns about a header that failed parsing

```r
httr::GET("https://open.canada.ca/data/en/api/3/action/status_show")
#> Response [https://open.canada.ca/data/en/api/3/action/status_show]
#>   Date: 2020-11-24 02:11
#>   Status: 200
#>   Content-Type: application/json;charset=utf-8
#>   Size: 460 B
#> 
#> Warning message:
#> Failed to parse headers:
#>     style-src 'self' 'unsafe-inline' maxcdn.bootstrapcdn.com netdna.bootstrapcdn.com *.gc.ca *.open.canada.ca *.canada.ca fonts.googleapis.com platform.twitter.com cdn.datatables.net cdn.jsdelivr.net use.fontawesome.com *.foresee.com;
#>     font-src 'self' maxcdn.bootstrapcdn.com netdna.bootstrapcdn.com *.open.canada.ca *.canada.ca fonts.googleapis.com fonts.gstatic.com cdn.jsdelivr.net use.fontawesome.com *.foresee.com;
#>     object-src 'self' *.open.canada.ca *.canada.ca www.youtube.com youtube.com *.gc.ca;
#>     media-src 'self' *.open.canada.ca *.canada.ca *.gc.ca www.youtube.com youtube.com epsg.io
```

But in crul we throw an error

```r
crul::HttpClient$new("https://open.canada.ca/data/en/api/3/action/status_show")$get()
#> Error in xx[[2]] : subscript out of bounds

traceback()
#> 10: tolower(xx[[2]])
#> 9: stats::setNames(xx[[3]], tolower(xx[[2]]))
#> 8: as.list(stats::setNames(xx[[3]], tolower(xx[[2]])))
#> 7: FUN(X[[i]], ...)
#> 6: lapply(x, head_parse)
#> 5: do.call("c", lapply(x, head_parse))
#> 4: FUN(X[[i]], ...)
#> 3: lapply(curl::parse_headers(hh, multiple = TRUE), headers_parse)
#> 2: private$make_request(rr)
#> 1: crul::HttpClient$new("https://open.canada.ca/data/en/api/3/action/status_show")$get()
```

**Comment by KevCaz** [comment]
Hi @sckott, I ran into the smae problem while working on [rgovcan](https://github.com/VLucet/rgovcan) (maintained by @VLucet) for which we are using ckanr. Basically the following code

```R
x <- HttpClient$new(url = "https://open.canada.ca/data/en/data
   set") 
   x$verb('get')
```
throws the error you're reporting above. This was not a problem a month ago but today it was. Not sure what happened in between but I've tried to find out what was the issue, looks like it is due to the following lines in `R/headers.R` (which is basically what you mention above):

https://github.com/ropensci/crul/blob/b9d94366f68cea1f77b6f81258e00b9175815b11/R/headers.R#L1-L9

IMHO, one simple way to deal with this is to test the length of `xx`

```R
if (length(xx) == 3) as.list(stats::setNames(xx[[3]], tolower(xx[[2]])))
```

which could be used to throw a warning as you suggest. This may be a quick and dirty solution.... It may be worth adding a first `grepl()`: 

```R
head_parse <- function(z) {
  if (grepl("HTTP\\/", z)) {
    list(status = z)
  } else {
    if (grepl("^([^:]*):\\s*(.*)$", z)) {
      ff <- regexec("^([^:]*):\\s*(.*)$", z)
      xx <- regmatches(z, ff)[[1]]
      as.list(stats::setNames(xx[[3]], tolower(xx[[2]])))
    } else {
      warning("Failed to parse headers:\n", z)
    }
  
  }
}
```

These are just some thoughts to fix this, I guess you have better ideas to do this properly! In the meanwhile, any suggestion to overcome this with the current version of `crul`?

**Comment by sckott** [comment]
Thanks @KevCaz ! Can't think of an immediate work around, but hoping I can't get this fixed today so you can install dev version

**Comment by sckott** [comment]
@KevCaz should work now, install from here

**Comment by KevCaz** [comment]
Thanks @sckott, it's working! 

So now we get a warning, is there a better way than using `suppressWarnings()` to get rid of expected warnings?

**Comment by sckott** [comment]
You've probably noticed tidyverse warnings get handled in a special way in that you only see them once per R session. I implemented that in a package https://github.com/ropensci/conditionz - there might be other solutions out there

**Comment by KevCaz** [comment]
I'll have a look at `conditionz`.
