### ISSUE TITLE
user agent

### ISSUE THREAD

**Issue by maelle** [ropensci/crul#63]
Is [this](https://github.com/ropensci/opencage/blob/devel/R/utils.R#L45) the right way to set a custom user agent?

If it is, I could do a PR to add this in the docs... in the file where you think it'd make sense. 😸

**Comment by sckott** [comment]
blah, so i had forgotten about this. I do need to fix this. You can set user agent as a curl option OR a header. right now in this pkg if you set `opts = list(useragent = "foo bar")` it is ignored because we set a default user agent (just like httr does), but I need to fix to not set the default user agent if the user has passed in either a `useragent` curl option or a `User-Agent` header. 

for now, you can set it as a header as you have in https://github.com/ropensci/opencage/blob/devel/R/utils.R#L45

once I fix this then you can set as a header or a curl option

**Comment by sckott** [comment]
okay, fixed

**Comment by maelle** [comment]
Ok thanks. Is there any reason for me to change the current code in `opencage`, i.e. is it better to use a curl option rather than a header (as I do know if I understand correctly 😸 ) or are both solutions equivalent?

**Comment by sckott** [comment]
Either way is good. I don't know of any reason why one is better than the other
